name: build_pos_binary
on:
  push:
    branches: [ main ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    name: build
    runs-on: [so0]
    defaults:
      run:
        shell: bash
    steps:
      - name: init
        run: |
            sudo rm -rf ${{github.workspace}}/*
      - uses: actions/checkout@v2
      - run: | 
          echo "update apt and install build tool"
          sudo apt-get update
          sudo apt-get install -y build-essential python wget libssl-dev libaio-dev vim git --fix-missing
          
      - run: |
          echo "Download required packages"
          sudo ./pkgdep.sh
        working-directory: ${{github.workspace}}/script

      - run: |
          echo "Build dependent libraries"
          sudo ./build_lib.sh
        working-directory: ${{github.workspace}}/lib

      - run: |
          echo "Configure src"
          sudo ./configure
        working-directory: ${{github.workspace}}/

      - run: |
          echo "Build src"
          sudo make -j 40
        working-directory: ${{github.workspace}}/
   
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: pos_binary
          path: |
            ${{github.workspace}}/bin/*

      - run: |
          echo "Clean up"
          sudo rm -rf ${{github.workspace}}/*
  nportest:
    name: npor_test
    needs: [build]
    runs-on: [so0]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - run : mkdir ${{github.workspace}}/bin
      - name: getbinary
        uses: actions/download_artifact@v2
        with:
          name: pos_binary
          path: ${{github.workspace}}/bin
      - name: test
        run: ./npor_test.sh -f 127.0.0.1
        working-directory: ${{github.workspace}}/test/regression
  sportest:
    name: spor_test
    needs: [build]
    runs-on: [so0]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - run : mkdir ${{github.workspace}}/bin
      - name: getbinary
        uses: actions/download_artifact@v2
        with:
          name: pos_binary
          path: ${{github.workspace}}/bin
      - name: test
        run: ./spor_test.sh -f 127.0.0.1
        working-directory: ${{github.workspace}}/test/regression



